#include<iostream.h>
#include<conio.h>
void main(){
clrscr();
int a;
cout<<"enter your no. = ";
cin>>a;
cout<<a<<" X 1 = "<<a*1;
cout<<"\n"<<a<<" X 2 = "<<a*2;
cout<<"\n"<<a<<" X 3 = "<<a*3;
cout<<"\n"<<a<<" X 4 = "<<a*4;
cout<<"\n"<<a<<" X 5 = "<<a*5;
cout<<"\n"<<a<<" X 6 = "<<a*6;
cout<<"\n"<<a<<" X 7 = "<<a*7;
cout<<"\n"<<a<<" X 8 = "<<a*8;
cout<<"\n"<<a<<" X 9 = "<<a*9;
cout<<"\n"<<a<<" X 10 = "<<a*10;
getch();
}